<?php

namespace AppBundle\Repository;

use Gedmo\Sortable\Entity\Repository\SortableRepository;

/**
 * MealOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MealOptionRepository extends SortableRepository
{
}
