<?php

namespace AppBundle\Repository;

use Gedmo\Sortable\Entity\Repository\SortableRepository;
/**
 * MealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MealRepository extends SortableRepository
{
}
