<?php

namespace AppBundle\Repository;

/**
 * OrderItemOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderItemOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
