# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.json_api_serializer:
        class: League\Fractal\Serializer\JsonApiSerializer

    app.serializer.manager:
        class: League\Fractal\Manager
        calls:
            - ["setSerializer", ["@app.json_api_serializer"]]

    app.serializer.transformer.meal:
        class: AppBundle\Transformer\Entity\MealTransformer

    app.serializer.transformer.meal_option:
        class: AppBundle\Transformer\Entity\MealOptionTransformer

    serialize_listener:
        class: AppBundle\Event\Listener\SerializeListener
        arguments: ["@app.serializer.manager", "@app.serializer.transformer.meal", "@app.serializer.transformer.meal_option"]
        tags:
            - { name: doctrine.orm.entity_listener }
